language: rust
rust: nightly-2018-04-19
cache: cargo
before_install:
  - rustup component add rustfmt-preview
  # - cargo install clippy -f --vers=0.0.195
env:
  global:
    - RUST_BACKTRACE=1
    - RUSTFLAGS="-D warnings"
  script:
    - cargo fmt -- --write-mode=diff
    # TODO: Enable Clippy once https://github.com/rust-lang/rust/issues/49643
    #       has been resolved. Add tests.
    # - cargo clippy -- -D clippy
    # - cargo clippy --tests -- -D clippy
    # - cargo check --tests
    - cargo test
